type AutoGenerated []struct {
	RowIdx int `json:"row_idx"`
	Row    struct {
		Text           string    `json:"text"`
		URL            string    `json:"url"`
		TopChoiceIndex int       `json:"top_choice_index"`
		TopChoiceProb  float64   `json:"top_choice_prob"`
		TopChoice      string    `json:"top_choice"`
		ChoiceProbs    []float64 `json:"choice_probs"`
		ChoiceLoss     []float64 `json:"choice_loss"`
		Metadata       struct {
			ContentLength             string      `json:"Content-Length"`
			ContentType               string      `json:"Content-Type"`
			WARCBlockDigest           string      `json:"WARC-Block-Digest"`
			WARCConcurrentTo          string      `json:"WARC-Concurrent-To"`
			WARCDate                  time.Time   `json:"WARC-Date"`
			WARCIPAddress             string      `json:"WARC-IP-Address"`
			WARCIdentifiedPayloadType string      `json:"WARC-Identified-Payload-Type"`
			WARCPayloadDigest         string      `json:"WARC-Payload-Digest"`
			WARCRecordID              string      `json:"WARC-Record-ID"`
			WARCTargetURI             string      `json:"WARC-Target-URI"`
			WARCTruncated             interface{} `json:"WARC-Truncated"`
			WARCType                  string      `json:"WARC-Type"`
			WARCWarcinfoID            string      `json:"WARC-Warcinfo-ID"`
		} `json:"metadata"`
		LabelPermutation   []int `json:"label_permutation"`
		FewshotPermutation []int `json:"fewshot_permutation"`
	} `json:"row"`
	TruncatedCells []interface{} `json:"truncated_cells"`
}type AutoGenerated []struct {
	RowIdx int `json:"row_idx"`
	Row    struct {
		Text           string    `json:"text"`
		URL            string    `json:"url"`
		TopChoiceIndex int       `json:"top_choice_index"`
		TopChoiceProb  float64   `json:"top_choice_prob"`
		TopChoice      string    `json:"top_choice"`
		ChoiceProbs    []float64 `json:"choice_probs"`
		ChoiceLoss     []float64 `json:"choice_loss"`
		Metadata       struct {
			ContentLength             string      `json:"Content-Length"`
			ContentType               string      `json:"Content-Type"`
			WARCBlockDigest           string      `json:"WARC-Block-Digest"`
			WARCConcurrentTo          string      `json:"WARC-Concurrent-To"`
			WARCDate                  time.Time   `json:"WARC-Date"`
			WARCIPAddress             string      `json:"WARC-IP-Address"`
			WARCIdentifiedPayloadType string      `json:"WARC-Identified-Payload-Type"`
			WARCPayloadDigest         string      `json:"WARC-Payload-Digest"`
			WARCRecordID              string      `json:"WARC-Record-ID"`
			WARCTargetURI             string      `json:"WARC-Target-URI"`
			WARCTruncated             interface{} `json:"WARC-Truncated"`
			WARCType                  string      `json:"WARC-Type"`
			WARCWarcinfoID            string      `json:"WARC-Warcinfo-ID"`
		} `json:"metadata"`
		LabelPermutation   []int `json:"label_permutation"`
		FewshotPermutation []int `json:"fewshot_permutation"`
	} `json:"row"`
	TruncatedCells []interface{} `json:"truncated_cells"`
}
